import { SaleItem, calculateRepasse, calculateLucro, calculatePorcentagem } from './types';

interface RawSaleSeed {
  marketplace: 'SHOPEE' | 'MERCADO LIVRE';
  data: string; // YYYY-MM-DD
  produto: string;
  material: 'PLA' | 'PETG' | 'PET-G';
  energia: number;
  filamento: number;
  manutencao: number;
  venda: number;
  taxa: number;
}

const rawSeeds: RawSaleSeed[] = [
  // Setembro 2026
  {
    marketplace: 'SHOPEE',
    data: '2026-09-01',
    produto: '20x Porta Bombom Pomo de Ouro Harry Potter 3D',
    material: 'PLA',
    energia: 3.20,
    filamento: 14.50,
    manutencao: 4.20,
    venda: 79.90,
    taxa: 15.98,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-09-02',
    produto: 'Adaptador Mini Bowens para Flash Speedlite',
    material: 'PETG',
    energia: 1.80,
    filamento: 11.20,
    manutencao: 3.36,
    venda: 68.00,
    taxa: 11.56,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-09-03',
    produto: 'Suporte Articulado Câmera Web Mesa Gamer',
    material: 'PET-G',
    energia: 2.50,
    filamento: 18.40,
    manutencao: 5.04,
    venda: 89.90,
    taxa: 15.28,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-09-04',
    produto: 'Vaso Geométrico Poligonal Nórdico 18cm',
    material: 'PLA',
    energia: 1.40,
    filamento: 8.80,
    manutencao: 2.52,
    venda: 45.00,
    taxa: 9.00,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-09-05',
    produto: 'Caixa Organizadora Modular Grid 6 Gavetas',
    material: 'PLA',
    energia: 4.10,
    filamento: 24.50,
    manutencao: 6.72,
    venda: 119.00,
    taxa: 23.80,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-09-06',
    produto: '20x Porta Bombom Pomo de Ouro Harry Potter 3D',
    material: 'PLA',
    energia: 3.20,
    filamento: 14.50,
    manutencao: 4.20,
    venda: 84.90,
    taxa: 14.43,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-09-07',
    produto: 'Adaptador Mini Bowens para Flash Speedlite',
    material: 'PETG',
    energia: 1.80,
    filamento: 11.20,
    manutencao: 3.36,
    venda: 68.00,
    taxa: 11.56,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-09-07',
    produto: 'Organizador de Cabos Magnético de Mesa (Kit 5un)',
    material: 'PLA',
    energia: 0.80,
    filamento: 4.20,
    manutencao: 1.68,
    venda: 29.90,
    taxa: 5.98,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-09-08',
    produto: 'Suporte Headset Gamer com Passa-Cabo',
    material: 'PETG',
    energia: 2.10,
    filamento: 16.00,
    manutencao: 4.20,
    venda: 74.90,
    taxa: 12.73,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-09-09',
    produto: 'Troféu Personalizado E-Sports 3D',
    material: 'PLA',
    energia: 3.80,
    filamento: 22.00,
    manutencao: 5.88,
    venda: 129.90,
    taxa: 25.98,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-09-10',
    produto: '20x Porta Bombom Pomo de Ouro Harry Potter 3D',
    material: 'PLA',
    energia: 3.20,
    filamento: 14.50,
    manutencao: 4.20,
    venda: 84.90,
    taxa: 14.43,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-09-10',
    produto: 'Adaptador Mini Bowens para Flash Speedlite',
    material: 'PET-G',
    energia: 1.80,
    filamento: 11.20,
    manutencao: 3.36,
    venda: 64.90,
    taxa: 12.98,
  },

  // Agosto 2026
  {
    marketplace: 'SHOPEE',
    data: '2026-08-02',
    produto: '20x Porta Bombom Pomo de Ouro Harry Potter 3D',
    material: 'PLA',
    energia: 3.20,
    filamento: 14.50,
    manutencao: 4.20,
    venda: 79.90,
    taxa: 15.98,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-08-04',
    produto: 'Adaptador Mini Bowens para Flash Speedlite',
    material: 'PETG',
    energia: 1.80,
    filamento: 11.20,
    manutencao: 3.36,
    venda: 68.00,
    taxa: 11.56,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-08-07',
    produto: 'Caixa Organizadora Modular Grid 6 Gavetas',
    material: 'PLA',
    energia: 4.10,
    filamento: 24.50,
    manutencao: 6.72,
    venda: 125.00,
    taxa: 21.25,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-08-11',
    produto: 'Suporte Articulado Câmera Web Mesa Gamer',
    material: 'PET-G',
    energia: 2.50,
    filamento: 18.40,
    manutencao: 5.04,
    venda: 84.90,
    taxa: 16.98,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-08-14',
    produto: 'Vaso Geométrico Poligonal Nórdico 18cm',
    material: 'PLA',
    energia: 1.40,
    filamento: 8.80,
    manutencao: 2.52,
    venda: 45.00,
    taxa: 9.00,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-08-18',
    produto: '20x Porta Bombom Pomo de Ouro Harry Potter 3D',
    material: 'PLA',
    energia: 3.20,
    filamento: 14.50,
    manutencao: 4.20,
    venda: 84.90,
    taxa: 14.43,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-08-21',
    produto: 'Suporte Headset Gamer com Passa-Cabo',
    material: 'PETG',
    energia: 2.10,
    filamento: 16.00,
    manutencao: 4.20,
    venda: 74.90,
    taxa: 12.73,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-08-25',
    produto: 'Organizador de Cabos Magnético de Mesa (Kit 5un)',
    material: 'PLA',
    energia: 0.80,
    filamento: 4.20,
    manutencao: 1.68,
    venda: 29.90,
    taxa: 5.98,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-08-28',
    produto: 'Adaptador Mini Bowens para Flash Speedlite',
    material: 'PETG',
    energia: 1.80,
    filamento: 11.20,
    manutencao: 3.36,
    venda: 68.00,
    taxa: 11.56,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-08-30',
    produto: 'Troféu Personalizado E-Sports 3D',
    material: 'PLA',
    energia: 3.80,
    filamento: 22.00,
    manutencao: 5.88,
    venda: 129.90,
    taxa: 25.98,
  },

  // Julho 2026
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-07-05',
    produto: 'Adaptador Mini Bowens para Flash Speedlite',
    material: 'PETG',
    energia: 1.80,
    filamento: 11.20,
    manutencao: 3.36,
    venda: 68.00,
    taxa: 11.56,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-07-10',
    produto: '20x Porta Bombom Pomo de Ouro Harry Potter 3D',
    material: 'PLA',
    energia: 3.20,
    filamento: 14.50,
    manutencao: 4.20,
    venda: 79.90,
    taxa: 15.98,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-07-16',
    produto: 'Vaso Geométrico Poligonal Nórdico 18cm',
    material: 'PLA',
    energia: 1.40,
    filamento: 8.80,
    manutencao: 2.52,
    venda: 45.00,
    taxa: 9.00,
  },
  {
    marketplace: 'MERCADO LIVRE',
    data: '2026-07-22',
    produto: 'Suporte Articulado Câmera Web Mesa Gamer',
    material: 'PET-G',
    energia: 2.50,
    filamento: 18.40,
    manutencao: 5.04,
    venda: 89.90,
    taxa: 15.28,
  },
  {
    marketplace: 'SHOPEE',
    data: '2026-07-28',
    produto: 'Caixa Organizadora Modular Grid 6 Gavetas',
    material: 'PLA',
    energia: 4.10,
    filamento: 24.50,
    manutencao: 6.72,
    venda: 119.00,
    taxa: 23.80,
  },
];

export function generateInitialSales(): SaleItem[] {
  return rawSeeds.map((seed, idx) => {
    const custo = Number((seed.energia + seed.filamento + seed.manutencao).toFixed(2));
    const repasse = calculateRepasse(seed.venda, seed.taxa);
    const lucro = calculateLucro(repasse, custo);
    const porcentagem = calculatePorcentagem(lucro, custo);

    return {
      id: `sale-${idx + 1}-${Date.now().toString(36)}`,
      marketplace: seed.marketplace,
      data: seed.data,
      produto: seed.produto,
      material: seed.material,
      energia: seed.energia,
      filamento: seed.filamento,
      manutencao: seed.manutencao,
      custo,
      venda: seed.venda,
      taxa: seed.taxa,
      repasse,
      lucro,
      porcentagem,
      source: 'manual',
      createdAt: new Date(seed.data + 'T12:00:00Z').toISOString(),
    };
  });
}
